// <auto-generated />
using System;
using Fahrplanauskunft.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Fahrplanauskunft.Infrastructure.Migrations
{
    [DbContext(typeof(FahrplanDbContext))]
    partial class FahrplanDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Fahrplanauskunft.Core.Entities.Footpath", b =>
                {
                    b.Property<string>("FromStopId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ToStopId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int?>("DistanceMeters")
                        .HasColumnType("integer");

                    b.Property<int>("Duration")
                        .HasColumnType("integer")
                        .HasColumnName("DurationMinutes");

                    b.Property<bool>("WheelchairAccessible")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.HasKey("FromStopId", "ToStopId");

                    b.HasIndex("FromStopId")
                        .HasDatabaseName("IX_Footpaths_FromStopId");

                    b.HasIndex("ToStopId")
                        .HasDatabaseName("IX_Footpaths_ToStopId");

                    b.HasIndex("ToStopId", "FromStopId")
                        .HasDatabaseName("IX_Footpaths_ToStopId_FromStopId");

                    b.ToTable("Footpaths", (string)null);
                });

            modelBuilder.Entity("Fahrplanauskunft.Core.Entities.Route", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Color")
                        .HasMaxLength(6)
                        .HasColumnType("character varying(6)");

                    b.Property<string>("LongName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("Mode")
                        .HasColumnType("integer");

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("TextColor")
                        .HasMaxLength(6)
                        .HasColumnType("character varying(6)");

                    b.HasKey("Id");

                    b.HasIndex("Mode")
                        .HasDatabaseName("IX_Routes_Mode");

                    b.HasIndex("ShortName")
                        .HasDatabaseName("IX_Routes_ShortName");

                    b.ToTable("Routes", (string)null);
                });

            modelBuilder.Entity("Fahrplanauskunft.Core.Entities.Stop", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Location")
                        .HasColumnType("text")
                        .HasColumnName("Location");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("PlatformCode")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<bool>("WheelchairAccessible")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .HasDatabaseName("IX_Stops_Name");

                    b.ToTable("Stops", (string)null);
                });

            modelBuilder.Entity("Fahrplanauskunft.Core.Entities.StopTime", b =>
                {
                    b.Property<string>("TripId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("Sequence")
                        .HasColumnType("integer");

                    b.Property<int>("Arrival")
                        .HasColumnType("integer")
                        .HasColumnName("ArrivalMinutes");

                    b.Property<int>("Departure")
                        .HasColumnType("integer")
                        .HasColumnName("DepartureMinutes");

                    b.Property<bool>("DropOffAllowed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<bool>("PickupAllowed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("StopId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("TripId", "Sequence");

                    b.HasIndex("Arrival")
                        .HasDatabaseName("IX_StopTimes_Arrival");

                    b.HasIndex("Departure")
                        .HasDatabaseName("IX_StopTimes_Departure");

                    b.HasIndex("StopId")
                        .HasDatabaseName("IX_StopTimes_StopId");

                    b.HasIndex("StopId", "Arrival")
                        .HasDatabaseName("IX_StopTimes_StopId_Arrival");

                    b.HasIndex("StopId", "Departure")
                        .HasDatabaseName("IX_StopTimes_StopId_Departure");

                    b.ToTable("StopTimes", (string)null);
                });

            modelBuilder.Entity("Fahrplanauskunft.Core.Entities.Trip", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Headsign")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("RouteId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ShortName")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("Headsign")
                        .HasDatabaseName("IX_Trips_Headsign");

                    b.HasIndex("RouteId")
                        .HasDatabaseName("IX_Trips_RouteId");

                    b.ToTable("Trips", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
